### ISSUE TITLE
Android: cannot find symbol class Nullable

### ISSUE THREAD

**Issue by larry-cherry** [talut/rn-secure-storage#35]
When updating from 1.1.1 to 2.0.1 I am experiencing an issue where Android is failing to build. Looking at the Android studio error it looks like it is caused by an import error in RNSecureStorageModule.java line 5 `import androidx.annotation.Nullable;`
![Screen Shot 2019-08-27 at 10 36 37 AM](https://user-images.githubusercontent.com/22753964/63786131-1ea1c780-c8b7-11e9-9eb9-131a036c57a7.png)

**Comment by talut** [comment]
@larry-cherry Hi, yes this package was updated to AndroidX at v2.0.1.  When Facebook was published v0.60 the android parts migrated to AndroidX. You can see blog post about this update from this url: https://facebook.github.io/react-native/blog/2019/07/03/version-60

I'll add this url to README.md do you have still any issue?
